google_app_secret: 123123
google_app_id: 123123
app_host: http://localhost
jwt_key: akjlehyuiAUSDh2
app_port: 8090
conf_broker:
  address: localhost:9092
conf_db:
  address: 127.0.0.1
  port: 4666
  user: user
  pass: password
  db_name: arch_auth_db
  max_connections: 10
  read_timeout: 1
  write_timeout: 1