jwt_key: akjlehyuiAUSDh2
app_port: 8091
conf_broker:
  address: localhost:9092
conf_db:
  address: 127.0.0.1
  port: 4667
  user: user
  pass: password
  db_name: arch_taks_db
  max_connections: 10
  read_timeout: 1
  write_timeout: 1